/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package home.tests.ipaddrcounter;

import java.io.File;
import java.io.IOException;
import java.util.zip.ZipFile;

public class App {
    public static void main(String[] args) throws IOException {
        try(var zip = new ZipFile(new File(args[0]), ZipFile.OPEN_READ)) {
            
        }
    }
}
